# A/B Testing Deployment Workflow
name: A/B Testing Deployment

on:
  workflow_dispatch:
    inputs:
      environment:
        description: 'Target Environment'
        required: true
        default: 'staging'
        type: choice
        options:
        - staging
        - production
      variant_a_percentage:
        description: 'Variant A traffic percentage (0-100)'
        required: false
        default: '50'
        type: string
      variant_b_percentage:
        description: 'Variant B traffic percentage (0-100)'
        required: false
        default: '50'
        type: string
      test_duration_hours:
        description: 'Test duration in hours'
        required: false
        default: '168'
        type: string
      success_metric:
        description: 'Primary success metric'
        required: false
        default: 'conversion_rate'
        type: choice
        options:
        - conversion_rate
        - revenue_per_user
        - engagement_rate
        - error_rate

env:
  HEALTH_CHECK_URL: ${{ vars.HEALTH_CHECK_URL || 'http://localhost:8080/health' }}
  TEST_DURATION: ${{ github.event.inputs.test_duration_hours || '168' }}
  
jobs:
  validate:
    name: Pre-deployment Validation
    runs-on: ubuntu-latest
    outputs:
      version_a: ${{ steps.version.outputs.version_a }}
      version_b: ${{ steps.version.outputs.version_b }}
      
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          
      - name: Determine Versions
        id: version
        run: |
          VERSION_A=$(git describe --tags --abbrev=0 2>/dev/null || echo "v1.0.0-${GITHUB_SHA::8}")
          VERSION_B=$(git describe --tags --abbrev=0 HEAD~1 2>/dev/null || echo "v2.0.0-${GITHUB_SHA::8}")
          echo "version_a=$VERSION_A" >> $GITHUB_OUTPUT
          echo "version_b=$VERSION_B" >> $GITHUB_OUTPUT
          echo "Variant A (Control): $VERSION_A"
          echo "Variant B (Test): $VERSION_B"
          
      - name: Validate Traffic Split
        run: |
          PCT_A=${{ github.event.inputs.variant_a_percentage || '50' }}
          PCT_B=${{ github.event.inputs.variant_b_percentage || '50' }}
          TOTAL=$((PCT_A + PCT_B))
          
          if [ $TOTAL -ne 100 ]; then
            echo "❌ Traffic split must equal 100% (A: $PCT_A%, B: $PCT_B% = $TOTAL%)"
            exit 1
          fi
          
          if [ $PCT_A -lt 0 ] || [ $PCT_A -gt 100 ] || [ $PCT_B -lt 0 ] || [ $PCT_B -gt 100 ]; then
            echo "❌ Traffic percentages must be between 0 and 100"
            exit 1
          fi
          
          echo "✅ Traffic split validation passed: A=$PCT_A%, B=$PCT_B%"
          
      - name: Validate Analytics Setup
        run: |
          echo "Checking analytics infrastructure..."
          # In production: Verify analytics service availability
          # Check metrics collection endpoints
          echo "✅ Analytics setup validated"

  deploy-variants:
    name: Deploy A/B Test Variants
    runs-on: ubuntu-latest
    needs: validate
    environment: ${{ github.event.inputs.environment || 'staging' }}
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Environment Variables
        run: |
          echo "VERSION_A=${{ needs.validate.outputs.version_a }}" >> $GITHUB_ENV
          echo "VERSION_B=${{ needs.validate.outputs.version_b }}" >> $GITHUB_ENV
          echo "ENVIRONMENT=${{ github.event.inputs.environment || 'staging' }}" >> $GITHUB_ENV
          echo "PCT_A=${{ github.event.inputs.variant_a_percentage || '50' }}" >> $GITHUB_ENV
          echo "PCT_B=${{ github.event.inputs.variant_b_percentage || '50' }}" >> $GITHUB_ENV

      - name: Build Variant A (Control)
        run: |
          echo "Building Variant A (Control): $VERSION_A..."
          # In production: docker build -t app:$VERSION_A .
          sleep 2
          echo "✅ Variant A built"

      - name: Build Variant B (Test)
        run: |
          echo "Building Variant B (Test): $VERSION_B..."
          # In production: docker build -t app:$VERSION_B .
          sleep 2
          echo "✅ Variant B built"

      - name: Deploy Variant A
        run: |
          echo "🚀 Deploying Variant A (Control)..."
          echo "Version: $VERSION_A"
          echo "Traffic: $PCT_A%"
          
          # In production: kubectl apply -f k8s/variant-a-deployment.yaml
          # OR helm install variant-a ./charts/app --set version=$VERSION_A
          
          echo "✅ Variant A deployed"

      - name: Deploy Variant B
        run: |
          echo "🚀 Deploying Variant B (Test)..."
          echo "Version: $VERSION_B"
          echo "Traffic: $PCT_B%"
          
          # In production: kubectl apply -f k8s/variant-b-deployment.yaml
          # OR helm install variant-b ./charts/app --set version=$VERSION_B
          
          echo "✅ Variant B deployed"

      - name: Configure Traffic Splitting
        run: |
          echo "⚖️  Configuring traffic splitting..."
          echo "Variant A: $PCT_A%"
          echo "Variant B: $PCT_B%"
          
          # In production: Update Istio VirtualService or load balancer config
          # kubectl apply -f k8s/virtualservice-ab-test.yaml
          # OR update service mesh traffic splitting rules
          
          echo "✅ Traffic splitting configured"

      - name: Verify Both Variants
        run: |
          echo "🔍 Verifying both variants..."
          
          sleep 10
          
          # Check variant A health
          echo "Checking Variant A health..."
          # In production: kubectl get pods -l variant=a
          
          # Check variant B health
          echo "Checking Variant B health..."
          # In production: kubectl get pods -l variant=b
          
          echo "✅ Both variants verified"

  monitor-ab-test:
    name: Monitor A/B Test
    runs-on: ubuntu-latest
    needs: [validate, deploy-variants]
    if: always()
    
    steps:
      - name: Set up A/B Test Monitoring
        run: |
          echo "📊 Setting up A/B test monitoring..."
          echo "Test duration: ${{ env.TEST_DURATION }} hours"
          echo "Success metric: ${{ github.event.inputs.success_metric || 'conversion_rate' }}"
          
          # In production: Set up analytics dashboards
          # Configure metrics collection for both variants
          
      - name: Monitor Test Metrics
        run: |
          echo "📈 Monitoring A/B test metrics..."
          echo ""
          echo "Key Metrics to Track:"
          echo "  - Conversion Rate (Variant A vs B)"
          echo "  - Revenue per User (Variant A vs B)"
          echo "  - Engagement Rate (Variant A vs B)"
          echo "  - Error Rate (Variant A vs B)"
          echo "  - Response Time (Variant A vs B)"
          echo ""
          echo "Monitoring for ${{ env.TEST_DURATION }} hours..."
          echo "(In production, this would run continuously)"
          
      - name: Collect Metrics Snapshot
        run: |
          echo "📸 Collecting metrics snapshot..."
          
          # In production: Query analytics service
          # Compare metrics between variants
          
          cat << EOF > ab-test-metrics.txt
          A/B Test Metrics Snapshot
          ========================
          Variant A (Control): ${{ needs.validate.outputs.version_a }}
          Variant B (Test): ${{ needs.validate.outputs.version_b }}
          Traffic Split: A=${{ github.event.inputs.variant_a_percentage || '50' }}%, B=${{ github.event.inputs.variant_b_percentage || '50' }}%
          
          Primary Metric: ${{ github.event.inputs.success_metric || 'conversion_rate' }}
          
          Variant A Metrics:
          - Conversion Rate: [To be populated]
          - Revenue per User: [To be populated]
          - Error Rate: [To be populated]
          
          Variant B Metrics:
          - Conversion Rate: [To be populated]
          - Revenue per User: [To be populated]
          - Error Rate: [To be populated]
          
          Statistical Significance: [To be calculated]
          Winner: [To be determined]
          EOF
          
          cat ab-test-metrics.txt
          
      - name: Upload Metrics Snapshot
        uses: actions/upload-artifact@v3
        with:
          name: ab-test-metrics
          path: ab-test-metrics.txt

  analyze-results:
    name: Analyze A/B Test Results
    runs-on: ubuntu-latest
    needs: [validate, deploy-variants, monitor-ab-test]
    if: always()
    
    steps:
      - name: Download Metrics
        uses: actions/download-artifact@v3
        with:
          name: ab-test-metrics
          
      - name: Calculate Statistical Significance
        run: |
          echo "📊 Calculating statistical significance..."
          echo ""
          echo "In production, this would:"
          echo "  1. Collect metrics from both variants"
          echo "  2. Calculate statistical significance (p-value)"
          echo "  3. Determine confidence intervals"
          echo "  4. Identify the winning variant"
          echo ""
          echo "✅ Analysis complete (simulated)"
          
      - name: Generate Test Report
        run: |
          echo "📋 Generating A/B test report..."
          
          cat << EOF > ab-test-report.txt
          A/B Test Results Report
          =======================
          Test Duration: ${{ env.TEST_DURATION }} hours
          Environment: ${{ github.event.inputs.environment || 'staging' }}
          Success Metric: ${{ github.event.inputs.success_metric || 'conversion_rate' }}
          
          Variants:
          - Variant A (Control): ${{ needs.validate.outputs.version_a }}
          - Variant B (Test): ${{ needs.validate.outputs.version_b }}
          
          Traffic Distribution:
          - Variant A: ${{ github.event.inputs.variant_a_percentage || '50' }}%
          - Variant B: ${{ github.event.inputs.variant_b_percentage || '50' }}%
          
          Results:
          - Statistical Significance: [To be calculated]
          - Confidence Level: [To be calculated]
          - Winner: [To be determined]
          - Improvement: [To be calculated]
          
          Recommendation: [To be populated after analysis]
          Next Steps: [To be determined]
          EOF
          
          cat ab-test-report.txt
          
      - name: Upload Test Report
        uses: actions/upload-artifact@v3
        with:
          name: ab-test-report
          path: ab-test-report.txt

  post-ab-test:
    name: Post A/B Test Actions
    runs-on: ubuntu-latest
    needs: [validate, deploy-variants, monitor-ab-test, analyze-results]
    if: always()
    
    steps:
      - name: Decision Point
        run: |
          echo "🎯 A/B Test Decision Point"
          echo "=========================="
          echo ""
          echo "Based on A/B test analysis:"
          echo "  [ ] Deploy winning variant to 100%"
          echo "  [ ] Continue test (insufficient data)"
          echo "  [ ] Abandon both variants"
          echo ""
          echo "Review the A/B test report artifact"
          echo "and ensure statistical significance before proceeding."
          
      - name: Send Notifications
        run: |
          echo "📢 Sending A/B test notifications..."
          # In production: Slack, email with test results
          echo "Team notified of A/B test status and results"

