apiVersion: v2
name: big-bang-app
description: A Helm chart for Big Bang deployment pattern
type: application
version: 0.1.0
appVersion: "1.0.0"
keywords:
  - deployment
  - big-bang
  - recreate
home: https://github.com/wbhankins93/deployment-patterns-guide
sources:
  - https://github.com/wbhankins93/deployment-patterns-guide
maintainers:
  - name: Ben Hankins
    email: benhankins.work@gmail.com